apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: youtrack-python-catalog
  description: Catalog entry point for the youtrack-python project
spec:
  type: file
  targets:
    - ./catalog/group.yaml
    - ./catalog/domain.yaml
    - ./catalog/system.yaml
    - ./catalog/component.yaml
    - ./catalog/postgres.yaml
    - ./catalog/youtrack.yaml
