apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-first-service
  description: test first project
  annotations:
    github.com/project-slug: kanenggg/youtrack-python
spec:
  type: service
  lifecycle: experimental
  owner: guest